import fs from 'fs';
import path from 'path';
import { Stream } from 'stream';

export interface SquadExportData {
  squadId: string;
  squadName: string;
  projectName: string;
  pages: PageContent[];
}

export interface PageContent {
  title: string;
  content: string;
  sections: Section[];
}

export interface Section {
  heading: string;
  content: string;
}

export interface ExportResult {
  success: boolean;
  filePath?: string;
  error?: string;
}

class NotionExportService {
  private templatesDir: string;

  constructor() {
    this.templatesDir = path.join(process.cwd(), '..', 'skills');
  }

  async generateExport(data: SquadExportData): Promise<string> {
    const { projectName, squadName, pages } = data;
    
    const sanitizedProject = this.sanitizeFileName(projectName);
    const sanitizedSquad = this.sanitizeFileName(squadName);
    
    const exportDir = path.join(process.cwd(), '..', '.tmp', 'exports', sanitizedProject, sanitizedSquad);
    
    if (!fs.existsSync(exportDir)) {
      fs.mkdirSync(exportDir, { recursive: true });
    }

    const createdFiles: string[] = [];

    for (const page of pages) {
      const fileName = `${this.sanitizeFileName(page.title)}.md`;
      const filePath = path.join(exportDir, fileName);
      
      const markdownContent = this.convertToMarkdown(page);
      fs.writeFileSync(filePath, markdownContent, 'utf-8');
      createdFiles.push(filePath);
    }

    const indexContent = this.generateIndexPage(pages, squadName);
    const indexPath = path.join(exportDir, 'README.md');
    fs.writeFileSync(indexPath, indexContent, 'utf-8');
    createdFiles.push(indexPath);

    return exportDir;
  }

  private convertToMarkdown(page: PageContent): string {
    let markdown = `# ${page.title}\n\n`;

    for (const section of page.sections) {
      markdown += `## ${section.heading}\n\n`;
      markdown += `${section.content}\n\n`;
    }

    return markdown;
  }

  private generateIndexPage(pages: PageContent[], squadName: string): string {
    let markdown = `# ${squadName}\n\n`;
    markdown += `*Generated by AgentPad - ${new Date().toLocaleDateString()}*\n\n`;
    markdown += `---\n\n`;
    markdown += `## Pages in This Section\n\n`;

    for (const page of pages) {
      const fileName = `${this.sanitizeFileName(page.title)}.md`;
      markdown += `- [${page.title}](./${fileName})\n`;
    }

    markdown += `\n---\n\n`;
    markdown += `## How to Import to Notion\n\n`;
    markdown += `1. Download this folder as a ZIP\n`;
    markdown += `2. Go to Notion and click "Import"\n`;
    markdown += `3. Select "Markdown and ZIP"\n`;
    markdown += `4. Choose where to create the pages\n`;

    return markdown;
  }

  private sanitizeFileName(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9-_]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '')
      .toLowerCase();
  }

  async createZipArchive(exportDir: string): Promise<string> {
    const AdmZip = require('adm-zip');
    const zip = new AdmZip();
    
    const files = fs.readdirSync(exportDir);
    for (const file of files) {
      const filePath = path.join(exportDir, file);
      zip.addLocalFile(filePath);
    }

    const zipPath = exportDir + '.zip';
    zip.writeZip(zipPath);
    
    return zipPath;
  }

  getTemplatesForSquad(squadId: string): string[] {
    const squadTemplates: Record<string, string[]> = {
      discovery: [
        'product_vision',
        'problem_statement', 
        'target_market',
        'competitive_analysis',
        'business_case'
      ],
      research: [
        'user_personas',
        'journey_maps',
        'research_summary'
      ],
      product: [
        'okrs',
        'roadmap',
        'requirements',
        'prioritization'
      ],
      design: [
        'wireframes',
        'design_system',
        'ui_components'
      ],
      technical: [
        'architecture',
        'api_specs',
        'schema',
        'user_stories'
      ],
      qa: [
        'test_strategy',
        'test_cases'
      ],
      security: [
        'security_assessment',
        'compliance'
      ],
      data: [
        'kpis',
        'dashboards'
      ],
      growth: [
        'launch_plan',
        'marketing_channels',
        'pricing'
      ],
      iteration: [
        'health_checks',
        'scale_assessments',
        'release_notes'
      ]
    };

    return squadTemplates[squadId] || [];
  }

  loadSkillOutput(squadId: string, pageName: string): PageContent | null {
    const skillName = `${pageName}`;
    const skillPath = path.join(this.templatesDir, skillName);

    if (!fs.existsSync(skillPath)) {
      return {
        title: this.formatTitle(pageName),
        content: 'Content not available. Run the relevant skill to generate content.',
        sections: []
      };
    }

    const outputSchemaPath = path.join(skillPath, 'output-schema.md');
    if (!fs.existsSync(outputSchemaPath)) {
      return {
        title: this.formatTitle(pageName),
        content: 'Template available but no output generated yet.',
        sections: []
      };
    }

    const content = fs.readFileSync(outputSchemaPath, 'utf-8');
    
    return {
      title: this.formatTitle(pageName),
      content: content,
      sections: this.parseSections(content)
    };
  }

  private parseSections(content: string): Section[] {
    const sections: Section[] = [];
    const lines = content.split('\n');
    let currentHeading = '';
    let currentContent: string[] = [];

    for (const line of lines) {
      if (line.startsWith('## ')) {
        if (currentHeading) {
          sections.push({
            heading: currentHeading,
            content: currentContent.join('\n').trim()
          });
        }
        currentHeading = line.replace('## ', '').trim();
        currentContent = [];
      } else if (currentHeading) {
        currentContent.push(line);
      }
    }

    if (currentHeading) {
      sections.push({
        heading: currentHeading,
        content: currentContent.join('\n').trim()
      });
    }

    return sections;
  }

  private formatTitle(name: string): string {
    return name
      .replace(/_/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());
  }
}

export const notionExportService = new NotionExportService();
